name: "Discord:congratsbot"

on:
  push:
    branches:
      - 'tools/congrats-bot-js-formatting'

jobs:
  congrats:
    name: "discord:congratsbot"
    runs-on: ubuntu-latest
    steps:
      - name: Send a Discord notification when a PR is merged
      
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_CONGRATS }}
          COMMIT_DATA: ${{ toJSON(github.events.commits[0]) }}
          # DISCORD_AVATAR: ${{ github.event.pull_request.user.avatar_url }}
        run: 'echo $COMMIT_DATA'
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: '**Sweet!** <${{ github.event.commits[0].author.name }}> just merged ["${{ github.event.commits[0].message }}"](<https://github.com/snowpackjs/astro/commits/main>)'
   
